import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: "class",
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        "surface-container": "#1c1f2a",
        "on-surface": "#dfe2f1",
        "on-secondary-fixed": "#23005c",
        "surface-container-low": "#171b26",
        "on-background": "#dfe2f1",
        "error": "#ffb4ab",
        "on-primary": "#003640",
        "on-secondary-fixed-variant": "#5516be",
        "primary": "#4cd7f6",
        "primary-fixed-dim": "#4cd7f6",
        "background": "#0f131d",
        "surface-dim": "#0f131d",
        "on-secondary-container": "#c4abff",
        "on-primary-fixed-variant": "#004e5c",
        "surface-container-lowest": "#0a0e18",
        "on-surface-variant": "#bcc9cd",
        "secondary-fixed-dim": "#d0bcff",
        "on-tertiary": "#003824",
        "primary-container": "#06b6d4",
        "inverse-primary": "#00687a",
        "tertiary-fixed-dim": "#4edea3",
        "outline-variant": "#3d494c",
        "tertiary": "#4edea3",
        "on-tertiary-fixed": "#002113",
        "surface-variant": "#313540",
        "surface": "#0f131d",
        "secondary": "#d0bcff",
        "surface-bright": "#353944",
        "on-tertiary-fixed-variant": "#005236",
        "inverse-surface": "#dfe2f1",
        "surface-container-high": "#262a35",
        "tertiary-fixed": "#6ffbbe",
        "on-error-container": "#ffdad6",
        "inverse-on-surface": "#2c303b",
        "on-secondary": "#3c0091",
        "primary-fixed": "#acedff",
        "error-container": "#93000a",
        "surface-tint": "#4cd7f6",
        "secondary-container": "#571bc1",
        "on-error": "#690005",
        "surface-container-highest": "#313540",
        "tertiary-container": "#1bbd85",
        "on-primary-fixed": "#001f26",
        "on-primary-container": "#00424f",
        "on-tertiary-container": "#00452e",
        "outline": "#869397",
        "secondary-fixed": "#e9ddff",
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        sm: "0.125rem",
        md: "0.25rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem",
      },
      spacing: {
        "space-xs": "0.25rem",
        "space-sm": "0.5rem",
        "space-md": "0.75rem",
        "space-lg": "1rem",
        "space-xl": "1.5rem",
        "gutter": "0.75rem",
        "gutter-desktop": "1rem",
        "margin": "1rem",
        "margin-desktop": "1.5rem",
      },
      fontFamily: {
        "headline-lg": ["var(--font-plus-jakarta)", "Plus Jakarta Sans", "sans-serif"],
        "headline-md": ["var(--font-plus-jakarta)", "Plus Jakarta Sans", "sans-serif"],
        "headline-sm": ["var(--font-plus-jakarta)", "Plus Jakarta Sans", "sans-serif"],
        "display-lg": ["var(--font-plus-jakarta)", "Plus Jakarta Sans", "sans-serif"],
        "display-lg-mobile": ["var(--font-plus-jakarta)", "Plus Jakarta Sans", "sans-serif"],
        "body-lg": ["var(--font-inter)", "Inter", "sans-serif"],
        "body-md": ["var(--font-inter)", "Inter", "sans-serif"],
        "body-sm": ["var(--font-inter)", "Inter", "sans-serif"],
        "label-md": ["var(--font-inter)", "Inter", "sans-serif"],
        "code-lg": ["var(--font-jetbrains-mono)", "JetBrains Mono", "monospace"],
        "code-md": ["var(--font-jetbrains-mono)", "JetBrains Mono", "monospace"],
        "code-sm": ["var(--font-jetbrains-mono)", "JetBrains Mono", "monospace"],
        "label-sm": ["var(--font-jetbrains-mono)", "JetBrains Mono", "monospace"],
      },
      fontSize: {
        "display-lg": ["36px", { lineHeight: "44px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "display-lg-mobile": ["28px", { lineHeight: "36px", letterSpacing: "-0.01em", fontWeight: "700" }],
        "headline-lg": ["28px", { lineHeight: "36px", letterSpacing: "-0.015em", fontWeight: "600" }],
        "headline-md": ["22px", { lineHeight: "28px", letterSpacing: "-0.01em", fontWeight: "600" }],
        "headline-sm": ["18px", { lineHeight: "24px", letterSpacing: "-0.005em", fontWeight: "600" }],
        "body-lg": ["15px", { lineHeight: "22px", letterSpacing: "0em", fontWeight: "400" }],
        "body-md": ["13px", { lineHeight: "18px", letterSpacing: "0em", fontWeight: "400" }],
        "body-sm": ["12px", { lineHeight: "16px", letterSpacing: "0.01em", fontWeight: "400" }],
        "code-lg": ["13px", { lineHeight: "18px", letterSpacing: "-0.01em", fontWeight: "500" }],
        "code-md": ["12px", { lineHeight: "16px", letterSpacing: "0em", fontWeight: "400" }],
        "code-sm": ["11px", { lineHeight: "14px", letterSpacing: "0.02em", fontWeight: "400" }],
        "label-md": ["11px", { lineHeight: "14px", letterSpacing: "0.05em", fontWeight: "600" }],
        "label-sm": ["10px", { lineHeight: "12px", letterSpacing: "0.08em", fontWeight: "600" }],
      },
    },
  },
  plugins: [],
};

export default config;
